apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: financeme
          image: allanroxen/medicure-project:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
