apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeme
  template:
    metadata:
      labels:
        app: financeme
    spec:
      containers:
        - name: financeme
          image: allanroxen/financeme-project:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
